{% set name = "cardiac-mps" %}
{% set name_underscore = "cardiac_mps" %}
{% set version = "2025.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name_underscore }}-{{ version }}.tar.gz"
  sha256: 978f0d186c25f8a5ebea343d155f53ea0b4ac379fbbcce6ec442a99bfee34bcc

build:
  number: 0
  noarch: python
  entry_points:
    - "mps=mps.__main__:app"
    - "mps2mp4=mps.__main__:run_mps2mp4"
    - "mps-summary=mps.__main__:run_summary"
    - "mps-analyze=mps.__main__:run_analyze"
    - "mps-motion=mps.__main__:run_motion"
  script: python -m pip install -v --no-deps .

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - ap_features
    - imageio
    - imageio-ffmpeg
    - matplotlib-base
    - numpy
    - scipy
    - tifffile
    - typer
    - xmltodict
test:
  imports:
    - mps

  requires:
    - pip
    - python {{ python_min }}

  commands:
    - pip check
    - mps --help

about:
  home: https://github.com/ComputationalPhysiology/mps
  summary: Tools for working with cardiac mps files
  license: LGPL-2.1-or-later AND BSD-3-Clause AND BSD-2-Clause
  license_file:
    - LICENSE
    - licenses/LICENSE_czifile
    - licenses/LICENSE_nd2file
    - licenses/LICENSE_tifffile
  doc_url: https://computationalphysiology.github.io/mps/
  dev_url: https://github.com/ComputationalPhysiology/mps

extra:
  recipe-maintainers:
    - finsberg
