{% set name = "cardiac-mps" %}
{% set name_underscore = "cardiac_mps" %}
{% set version = "2023.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name_underscore }}-{{ version }}.tar.gz"
  sha256: 362df9d5799ae84ba670fd14e88013fe476427e7776ede941bf10f1750c7194f

build:
  number: 0
  noarch: python
  entry_points:
    - "mps=mps.__main__:app"
    - "mps2mp4=mps.__main__:run_mps2mp4"
    - "mps-summary=mps.__main__:run_summary"
    - "mps-analyze=mps.__main__:run_analyze"
    - "mps-motion=mps.__main__:run_motion"
  script: python -m pip install -v --no-deps .

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - ap_features
    - imageio
    - imageio-ffmpeg
    - matplotlib-base
    - numpy
    - scipy
    - tifffile
    - typer
    - xmltodict
test:
  imports:
    - mps

  requires:
    - pip

  commands:
    - pip check
    - mps --help

about:
  home: https://github.com/ComputationalPhysiology/mps
  summary: Tools for working with cardiac mps files
  license: LGPL-2.1-or-later AND BSD-3-Clause AND BSD-2-Clause
  license_file:
    - LICENSE
    - licenses/LICENSE_czifile
    - licenses/LICENSE_nd2file
    - licenses/LICENSE_tifffile
  doc_url: https://computationalphysiology.github.io/mps/
  dev_url: https://github.com/ComputationalPhysiology/mps

extra:
  recipe-maintainers:
    - finsberg
